# Note: we need to use "raw" command unless python on destination is updated to 3.8
---
- name: Test Checkpoint Firewall Connection
  hosts: checkpoint-devct-firewalls
  connection: ssh  # Changed from httpapi to ssh
  gather_facts: false

  tasks:
    - name: Run test command
      ansible.builtin.raw: "echo 'Hello world!' && hostname"  # or any other bash command
      register: command_output

    - name: Display output
      debug:
        var: command_output.stdout
